name: Pubudu's Blog
markdown: kramdown
highlighter: rouge
description: "Pubudu Welagedara's Blog"
url: "welagedara.github.io"
permalink: /posts/:title

#srcset, sizes and dynamic media related
artifact_base: /artifacts
default_width: '1000'
sizes: '(min-width: 1020px) 60vw, 90vw'

srcset:
  - 600
  - 850
  - 1200

plugins:
  - jemoji