name: Dat site title tho
markdown: redcarpet
pygments: true
description: "Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
url: "welagedara.github.io"
permalink: /posts/:title